version: "3"

services:
  webapp:
    build: ./frontend
    image: agenda/webapp
    container_name: agenda-webapp
    stdin_open: true
    ports:
      - "3000:3000"
    networks:
      - agenda-network
    environment:
      # - API_AGENDA=http://34.237.243.233:5001
      - API_AGENDA=http://localhost:5001
    depends_on:
      - api
    command: yarn start

  api:
    build: ./backend
    image: agenda/api
    container_name: agenda-api
    ports:
      - "5001:80"
    networks:
      - agenda-network
    command: dotnet Api.dll

networks:
  agenda-network:
    name: agenda-network
    driver: bridge
